### PR TITLE
#150 db type file config cli

### LINKED ISSUE #150: Using db type in config files with CLI does not work

### PR DESCRIPTION
**Pull request by Lysoun**
Read db type from file config & override with arguments, just like any other setting

Fixes #150

### CODE REVIEW

File: modules/cli/src/main/kotlin/datamaintain/cli/App.kt [hunk 1]
```diff
@@ -47,10 +46,10 @@ class App : CliktCommand() {
             props.load(it.inputStream())
         }
         overloadPropsFromArgs(props)
-        props.put("dbType", dbType)
     }
 
     private fun overloadPropsFromArgs(props: Properties) {
+        dbType?.let { props[CoreConfigKey.DB_TYPE.key] = it }
```
Comment (driccio) [inline modules/cli/src/main/kotlin/datamaintain/cli/App.kt:52]: If you see on my PR I also do an other check and put to be backward compatible.

**Review by driccio — COMMENTED** [review]
Please see my comment. For the rest all is good (and better than my work :-) )

File: modules/cli/src/main/kotlin/datamaintain/cli/App.kt (hunk 1 above)
Comment (Lysoun) [reply modules/cli/src/main/kotlin/datamaintain/cli/App.kt:52]: Yes very good idea, I added backward compatibility!

**Review by driccio — APPROVED** [review]
