### PR TITLE
#39 Log a warning when failing to mark a script as executed

### LINKED ISSUE #39: Log a warning when failing to mark a script as executed
Display a warning when DataMaintain failed to mark a script as executed and give the user a command to solve the problem. This command could be the one to force a script as executed developed for issue #38

### PR DESCRIPTION
**Pull request by asolovieff**
Resolves #39

### CODE REVIEW

File: modules/driver-jdbc/src/main/kotlin/datamaintain/db/driver/jdbc/JdbcDriver.kt [hunk 1]
```diff
@@ -3,14 +3,15 @@ package datamaintain.db.driver.jdbc
...
 import java.sql.Connection
 import java.sql.DriverManager
 import java.sql.ResultSet
 import java.sql.SQLException
 import java.util.*
 
-class JdbcDriver(jdbcUri: String) : DatamaintainDriver(jdbcUri) {
-    private val connection: Connection = DriverManager.getConnection(jdbcUri)
+class JdbcDriver(jdbcUri: String,
+                 private val connection: Connection = DriverManager.getConnection(jdbcUri)) : DatamaintainDriver(jdbcUri) {
```
Comment (Lysoun) [inline modules/driver-jdbc/src/main/kotlin/datamaintain/db/driver/jdbc/JdbcDriver.kt:21]: Giving the connection as attribute enables the user to provide a connection to another database than the one corresponding to the URI

File: modules/driver-jdbc/src/main/kotlin/datamaintain/db/driver/jdbc/JdbcDriverConfig.kt [hunk 2]
```diff
@@ -8,13 +8,14 @@ import mu.KotlinLogging
 import java.util.*
 
 private val logger = KotlinLogging.logger {}
+private const val DB_TYPE = "jdbc"
```
Comment (Lysoun) [inline modules/driver-jdbc/src/main/kotlin/datamaintain/db/driver/jdbc/JdbcDriverConfig.kt]: Isn't there an enum for db types? Maybe in the CLI. If it's there, it would be nice to move it to the core module and use it here, instead of a constant

File: modules/driver-mongo/src/main/kotlin/datamaintain/db/driver/mongo/MongoDriverConfig.kt [hunk 3]
```diff
@@ -9,6 +11,7 @@ import java.nio.file.Paths
 import java.util.*
 
 private val logger = KotlinLogging.logger {}
+private const val DB_TYPE = "mongo"
```
Comment (Lysoun) [inline modules/driver-mongo/src/main/kotlin/datamaintain/db/driver/mongo/MongoDriverConfig.kt]: Use enum

File: modules/core/src/main/kotlin/datamaintain/core/step/executor/Executor.kt [hunk 4]
```diff
@@ -73,8 +74,13 @@ class Executor(private val context: Context) {
                 logger.info {"start marking script ${script.name} as executed"}
                 val executedScript = ExecutedScript.build(script, Execution(ExecutionStatus.OK), context.config.flags)
 
-                markAsExecuted(executedScript)
-                if (!context.config.porcelain) { logger.info { "${executedScript.name} only marked as executed (so not executed)" } }
+                try {
+                    markAsExecuted(executedScript)
+                    if (!context.config.porcelain) { logger.info { "${executedScript.name} only marked as executed (so not executed)" } }
+                } catch (e: DatamaintainQueryException) {
+                    logger.warn { "Failed to mark script $executedScript as executed. Use the following command to force mark the script as executed : " +
```
Comment (Lysoun) [inline modules/core/src/main/kotlin/datamaintain/core/step/executor/Executor.kt]: Printing the whole script may be a little bit too ambitious. Maybe the path to the file would be enough? Or just the name?

File: modules/core/src/main/kotlin/datamaintain/core/step/executor/Executor.kt [hunk 5]
```diff
@@ -73,8 +74,13 @@ class Executor(private val context: Context) {
...
+                            "./datamaintain-cli --db-type ${context.config.driverConfig.dbType} --db-uri ${context.config.driverConfig.uri} update-db --path ${context.config.path} --identifier-regex ${executedScript.identifier} --action MARK_AS_EXECUTED" }
```
Comment (Lysoun) [inline modules/core/src/main/kotlin/datamaintain/core/step/executor/Executor.kt]: The regex that should be given here is not the script identifier, it's the regex in the config. Of course, it's not very important because that's a command to execute only one script so the identifiers are not important

File: modules/core/src/main/kotlin/datamaintain/core/util/exception/DatamaintainQueryException.kt [hunk 6]
```diff
@@ -0,0 +1,5 @@
+package datamaintain.core.util.exception
+
+import datamaintain.core.exception.DatamaintainBaseException
+
+open class DatamaintainQueryException(message: String) : DatamaintainBaseException(message, "")
```
Comment (Lysoun) [inline modules/core/src/main/kotlin/datamaintain/core/util/exception/DatamaintainQueryException.kt]: It appears that `""` is already the default value of the second argument of the `DatamaintainBaseException` constructor so there is no need to give the precision here

File: modules/driver-jdbc/src/main/kotlin/datamaintain/db/driver/jdbc/JdbcDriver.kt (hunk 1 above)
Comment (asolovieff) [reply modules/driver-jdbc/src/main/kotlin/datamaintain/db/driver/jdbc/JdbcDriver.kt:21]: But it helps me perform some test by giving my own connection
